
name: Dev-RSE
description: Enhancement or bug
title: "[RSEDev]: "
body:    
  - type: textarea
    id: request
    attributes:
      label: Details
      description: Enter details
      placeholder: details
    validations:
      required: true
