
name: Dev-RSE
description: Enhancement or bug
title: "[RSEDev]: "
body:    
  - type: input
    id: request
    attributes:
      label: Details
      description: Enter details:
      placeholder: details
    validations:
      required: true
  - type: markdown
    id: thanks
    attributes:
      value: "Thanks for completing our form!"
